### ISSUE TITLE
dsek.se/regelemete broken :disappointed: 

### ISSUE THREAD

**Issue by frednordell** [Dsek-LTH/reglemente#25]
dsek.se/regelemete redirectar till https://github.com/Dsek-LTH/reglemente/releases/download/latest/reglemente.pdf men den finns ej :disappointed: Det är nog för att output-filen heter main.pdf för https://github.com/Dsek-LTH/reglemente/releases/download/latest/main.pdf fungerar :smile:

**Comment by 01ste02** [comment]
Ser ingen anledning till detta. Kollar man i latest release finns reglemente.pdf, och allt fungerar med länken.
// root (som just börjat följa alla repos här och därför inte fått notifikation om ditt issue innan)
